#!/bin/bash

g++ ./source/main.cpp ./source/imgui/imgui_impl_glfw_gl3.cpp ./source/imgui/imgui_draw.cpp ./source/imgui/imgui.cpp -o visualize -std=c++11 -O2 -lGLEW -lglfw -lGL -lstdc++ -lm -lopencv_core -lopencv_highgui -lopencv_imgproc